package org.firstinspires.ftc.teamcode.subsystems.States;

public enum SpecimenTransferState {
    SPECIMEN_TRANSFER_INIT, // b1=0
    SPECIMEN_ARM_GOING_TO_WALL,
    SPECIMEN_ARM_TO_WALL_DONE,
    SPECIMEN_ARM_TO_WALL_CLAW_OPEN,
    SPECIMEN_ARM_TO_WALL_CLAW_CLOSING,
    SPECIMEN_ARM_TO_WALL_CLAW_CLOSED,
    SPECIMEN_ARM_TO_WALL_LATCH_OFF,
    SPECIMEN_ARM_ROTATING_TO_FIELD,
    SPECIMEN_ARM_TO_FIELD_LATCH_ON,
}
